#Practical Question

####Ques 1:- Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

random_array = np.random.randint(1, 101, (3, 3))

print("Original array:")
print(random_array)

interchanged_array = random_array.T

print("\nInterchanged array:")
print(interchanged_array)

Original array:
[[74 92 91]
 [32 15 84]
 [52 71 86]]

Interchanged array:
[[74 32 52]
 [92 15 71]
 [91 84 86]]


####Ques 2:- Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
import numpy as np
array = np.arange(10)
array_2x5 = array.reshape(2, 5)
array_5x2 = array.reshape(5, 2)

print("Original array:", array)
print("\n2x5 array:", array_2x5)
print("\n5x2 array:", array_5x2)

Original array: [0 1 2 3 4 5 6 7 8 9]

2x5 array: [[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 array: [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


####Ques 3:- Create a 4x4 Numpy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
import numpy as np

array = np.random.rand(4, 4)

padded_array = np.pad(array, ((1, 1), (1, 1)), mode='constant', constant_values=0)

print("Original array:\n", array)
print("\nPadded array:\n", padded_array)

Original array:
 [[0.64369914 0.26480521 0.0505871  0.87152455]
 [0.56162914 0.95760812 0.08106786 0.76313824]
 [0.10359381 0.41884147 0.33119922 0.85491967]
 [0.87443665 0.31670078 0.82438737 0.82005294]]

Padded array:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.64369914 0.26480521 0.0505871  0.87152455 0.        ]
 [0.         0.56162914 0.95760812 0.08106786 0.76313824 0.        ]
 [0.         0.10359381 0.41884147 0.33119922 0.85491967 0.        ]
 [0.         0.87443665 0.31670078 0.82438737 0.82005294 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


####Ques 4:- Using NumPy, crate an array of integers from 10 to 60 with a step of 5

In [4]:
array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


#### Ques 5:- Create a NumPy array of string ['python, 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc). to each element.

In [8]:
import numpy as np

strings = np.array(['python', 'numpy', 'pandas'])
uppercase = np.char.upper(strings)
lowercase = np.char.lower(strings)
title_case = np.char.title(strings)

print("Original array:", strings)
print("\nUppercase:", uppercase)
print("\nLowercase:", lowercase)
print("\nTitle case:", title_case)

Original array: ['python' 'numpy' 'pandas']

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']

Lowercase: ['python' 'numpy' 'pandas']

Title case: ['Python' 'Numpy' 'Pandas']


####Ques 6:- Generate a Numpy array of words. Insert a space between each character of every word in the array.

In [9]:
import numpy as np


words = np.array(["hello", "world", "numpy"])

spaced_words = np.char.join(" ", words)

print(spaced_words)

['h e l l o' 'w o r l d' 'n u m p y']


####Ques 7:- Create two 2D Numpy arraysand perform element-wise addition, substraction, multiplication, and division.

In [2]:
import numpy as np

# Create two 2D Numpy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)

print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nMultiplication:\n", multiplication)
print("\nDivision:\n", division)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Multiplication:
 [[ 5 12]
 [21 32]]

Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


####Ques 8:- Use Numpy to create a 5x5 identity matrix, then extract its diagonal elements.

In [3]:
import numpy as np

identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

print("Identity matrix:\n", identity_matrix)
print("\nDiagonal elements:", diagonal_elements)

Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements: [1. 1. 1. 1. 1.]


####Ques 9:- Generate a Numpy array of 100 random integers between 0 and 1000, Find and display all prime numbers in this array.

In [4]:
import numpy as np

def is_prime(num):

  if num <= 1:
    return False
  if num <= 3:
    return True
  if num % 2 == 0 or num % 3 == 0:
    return False
  i = 5
  while i * i <= num:
    if num % i == 0 or num % (i + 2) == 0:
      return False
    i += 6
  return True

random_numbers = np.random.randint(0, 1001, 100)

prime_numbers = [num for num in random_numbers if is_prime(num)]

print("Random numbers:", random_numbers)
print("\nPrime numbers:", prime_numbers)

Random numbers: [  5  60 108  46 215 606 801 839 789  51 355 894  15 808 249 324 126  99
 252  98 222 101 171  77 130 439 335 857 494 710 284 168 872 193 848 849
 160 842 398 934  59 674 339 791 546 766 393 659 937  22 826 788 516 207
 537 188 773 198  85 338 985 241 733 805 200  21 906 459 111 466 874 898
   7 828  78 812 768 655 470 781 901  30 378 938 971 884 330 369 762 836
 746 254  54 918 354 132  78 848 538 335]

Prime numbers: [5, 839, 101, 439, 857, 193, 59, 659, 937, 773, 241, 733, 7, 971]


####Ques 10:- Create a Numpy array representing daily temperatures for a month. Calculate and display the weekly average.

In [5]:
import numpy as np

daily_temperatures = np.random.randint(60, 90, 30)

weekly_average = np.mean(daily_temperatures.reshape(5, 6), axis=1)

print("Daily temperatures:", daily_temperatures)
print("\nWeekly average:", weekly_average)

Daily temperatures: [67 79 89 71 60 85 64 76 87 66 62 69 77 73 85 61 79 78 73 71 87 80 74 73
 74 88 80 75 71 87]

Weekly average: [75.16666667 70.66666667 75.5        76.33333333 79.16666667]
